---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
#
# Run the following command to set up the pre-commit git hook scripts:
# $ pre-commit install
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-symlinks
      - id: destroyed-symlinks

      - id: check-json
      - id: check-yaml
      - id: check-xml

      - id: check-merge-conflict

  - repo: https://github.com/savonet/pre-commit-ocamlformat
    rev: v1.0.0
    hooks:
      - id: ocamlformat
