name: Build and test
on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_opam:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        ocaml-compiler:
          - 4.14.x
          - 5.2.x
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          opam-pin: true

      - name: Install camomile
        run: opam install -y --with-test camomile

      - name: Install camomile-embedded
        run: opam install -y --with-test camomile-embedded

      - name: Build with env config
        run: CAMOMILE_CONFIG=env CAMOMILE_PREFIX=/usr opam exec -- dune build -p camomile
